# name of the software
name: PSA Documentation


description: PSA documentation website
baseurl: "" # the subpath of the site, e.g. /blog
url: "https://developer.groupe-psa.io" # the base hostname & protocol for the site, e.g. http://example.com

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# WEB API BaseURI
webapiB2CProd: 
webapiB2CPreProd: "https://api-preprod.groupe-psa.com/connectedcar/v4"
webapiB2BProd: 
webapiB2BPreProd: "https://api-cert-preprod.groupe-psa.com/connectedcar/v3"
cvsOAuth2Prod: 
cvsOAuth2PreProd: "https://idpcvs-preprod.{brand.tld}/am/oauth2/access_token"
virtualKeyTokenProd: 
virtualKeyTokenPreProd: "https://api-preprod.groupe-psa.com/connectedcar/v3"
#End BaseURi

theme: jekyll-bulma

# Enable or disable the site search
search_enabled: true

collections:
  webportal-quick-start:
    output: true
  webportal-tutorials-advanced:
    output: true
  webportal-private-reference:
    output: true
  webportal-public-reference:
    output: true
  mobile-sdk-android-reference:
    output: true
  mobile-sdk-ios-reference:
    output: true

links:
    header:
    footer:

ui:
    header:
        color1: "#080331"
        color2: "#673051"

social:


analytics:

# Build settings
markdown: kramdown
highlighter: rouge
