# name of the software
title: PSA Groupe for developers
name: PSA Groupe for developers
description: Groupe PSA for Developers is the dedicated platform for application developers working with Groupe PSA's connected vehicles APIs and SDKs.
baseurl: "/groupepsa.github.io" # the subpath of the site, e.g. /blog
url: "https://etiennerobaglia.github.io" # the base hostname & protocol for the site, e.g. http://example.com


# github links
gitHubURL: "https://github.com/GroupePSA/groupepsa.github.io/tree/master/"
gitHubSpecB2B: "https://github.com/GroupePSA/groupepsa.github.io/blob/master/assets/openapi/api-b2b-webhook-template.yaml"
gitHubSpecB2C: "https://github.com/GroupePSA/groupepsa.github.io/blob/master/assets/openapi/psacc.yaml"

# doc versionning
versionWebportal: "1.5.3"
versionWebAPI: "1.7.1"
versionMobileSDK: "0.0.0"

# WEB API BaseURI - theses var have to be renamed without prod/preprod (because we display only one at once)
webapiB2CPreProd: "https://api.groupe-psa.com/connectedcar/v4"
webapiB2BPreProd: "https://api-cert.groupe-psa.com/connectedcar/{version}"
cvsOAuth2PreProd: "https://idpcvs.{brand.tld}/am/oauth2/access_token"
virtualKeyTokenPreProd: "https://api.groupe-psa.com/connectedcar/v3"

collections:
  webportal-quick-start:
    output: false
  webportal-tutorials-advanced:
    output: false
  webportal-private-reference:
    output: false
  webportal-public-reference:
    output: false
  mobile-sdk-android-reference:
    output: false
  mobile-sdk-ios-reference:
    output: false

exclude:
 - webapi/content/
 - mobile-sdk/content/
 - "node_modules/"
 - "*.gemspec"
 - "*.gem"
 - "Gemfile"
 - "Gemfile.lock"
 - "package.json"
 - "package-lock.json"
 - "script/"
 - "schema/"
 - "LICENSE.txt"
 - "lib/"
 - "bin/"
 - "README.md"
 - "Rakefile"

links:
    header:
    footer:

ui:
    header:
        color1: "#080331"
        color2: "#673051"

social:

analytics:

# Build settings
markdown: kramdown
highlighter: rouge

permalink: pretty

# Enable or disable the site search
search_enabled: true
